apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: book-catalog
    version: v1
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: alex6f/books-catalogue:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/booksrental"
            - name: SPRING_DATASOURCE_USERNAME
              value: "dbuser"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "dbpass"
          resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: book-catalog
  name: book-catalog-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
      app: book-catalog
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: book-service-proxy
spec:
  hosts:
    - "*"
  gateways:
    - project/microservice-gateway
  http:
    - match:
        - uri:
            prefix: /booksService/
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 80
            host: book-catalog-service.project.svc.cluster.local
