apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
    version: v1
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: alex6f/books-user:1  # Replace with your actual image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: BOOKS_SERVICE_URL
              value: "http://book-catalog-service:80"  # 🔄 Matches book service name
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service-service
spec:
  ports:
    - port: 80  # Exposes service inside the cluster
      protocol: TCP
      targetPort: 8081
      name: http
  selector:
    app: user-service
  type: ClusterIP  # Matches book-catalog-service
status:
  loadBalancer: {}

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-service-proxy
spec:
  hosts:
    - "*"
  gateways:
    - project/microservice-gateway
  http:
    - match:
        - uri:
            prefix: /userService/
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 80
            host: user-service-service.project.svc.cluster.local
